### ISSUE TITLE
pass original mouse event to callback

### ISSUE THREAD

**Issue by lekoala** [GeorgianStan/vanilla-context-menu#17]
would it be possible to pass along the mouse event that triggered the opening of the context menu in order to know what is the original element being concerned with the context menu? that would be super helpful

**Comment by lekoala** [comment]
@GeorgianStan sure, i have a calendar, i attach the context menu on the whole calendar. i want to copy paste events, so for the copy event, i need to know which event is under the context menu, and same thing for pasting, i need to know which day.
attaching distinct context menus to all events and rows is just not very practical in my case

**Comment by GeorgianStan** [comment]
If we send the `MouseEvent` as argument to the callback which is declared for elements inside the `menuItem` array would work for you?

**Comment by GeorgianStan** [comment]
Ok! I'll work on it and update the library. Thanks for your input!

**Comment by GeorgianStan** [comment]
The library was updated.
