### ISSUE TITLE
Impossible to concatenate HTML in labels :)

### ISSUE THREAD

**Issue by Lunar94** [GeorgianStan/vanilla-context-menu#19]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/105256980/178149726-de52465f-b218-4f9e-870f-9dd25d666e3b.png">

Here is the code I try:

```
document.querySelectorAll(".btn").forEach((element) => {
  const myContextMenu = new window.VanillaContextMenu({
    scope: element,
    menuItems: [
      {
        label:
          "<i class='fa-duotone fa-arrows-up-down-left-right'></i>" +
          "Assigner un raccourcis",
        callback: (event) => {
          console.log(event);
        },
      },
      {
        label: "Déplacer",
        callback: (event) => {
          console.log(event);
        },
      },
    ],
    customThemeClass: "custom-context",
  });
});
```

But here is the result:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/105256980/178149777-42ba69a6-574b-4918-bf02-31dbd8cf3ce9.png">

@GeorgianStan, I would really appreciate the help :3

**Comment by GeorgianStan** [comment]
Hi @Lunar94 sorry for the delayed response! From what I see you are trying to display an icon for each label. 
As of now there is no option to enable this feature.

I don't know if the insertion of raw HTML will be allowed or only if it will be some separate option for icons providing an icon.
I will work on that and update the library.
Thanks for your feedback!

**Comment by GeorgianStan** [comment]
Hi, @Lunar94. The library was updated and the new version enables icons as well.

**Comment by Lunar94** [comment]
@GeorgianStan Hi Georgian, I tested it all out when I came back from work, this is working flawlessly. Thank you very much, problem solved !

💯
