### ISSUE TITLE
Context menu only displays on first element of scope

### ISSUE THREAD

**Issue by cercos** [GeorgianStan/vanilla-context-menu#33]
When i set scope to document.querySelector('.someclasd')  context memu only works on first element with class.  My goal is to have every element with class.

**Comment by GeorgianStan** [comment]
Hi @cercos.
Do you think that this approach solves your problem?
```js
document.querySelectorAll('.someclasd').forEach((scope) => {
  const myContextMenu = new window.VanillaContextMenu({
    scope,
    menuItems: [
      {
        label: 'Option 1',
        callback: () => {
          console.log('Option 1 was clicked');
        },
      },
    ],
  });
});
```

**Comment by cercos** [comment]
@GeorgianStan Sorry.  I ended up opting for a hover tooltip instead of the approach I was using.  Never got to test if this worked.
