### ISSUE TITLE
Controlling the width of the menu + submenu

### ISSUE THREAD

**Issue by kla-ko** [GeorgianStan/vanilla-context-menu#44]
I'm using the ``customClass`` property to change the width of the context menu. I can change it by assigning a class definition which contains a ``width`` property, e.g., ``width:100px  !important`` 

This reduces the width of the menu and of the submenu. However, the gap between menu and submenu does not adapt accordingly. So the result looks  like this:

![image](https://user-images.githubusercontent.com/69795385/207395485-d83632dd-4c3f-4ee8-be50-ee31a4fd3ed0.png)

- Am I using the right way to change the menu width?
- If yes, the issue is that the positioning of the submenu is not adaptive.

Regards,

**Comment by GeorgianStan** [comment]
Hi, @kla-ko please try the latest version (v1.4.2).

**Comment by kla-ko** [comment]
Works like a charm.
Thank you!
